packageExtensions:
  follow-redirects@*:
    dependencies:
      debug: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  supports-color@*:
    dependencies:
      os: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  pg-query-stream@*:
    dependencies:
      pg: '*'
  typeorm@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      sqlite3: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220112.hash-947ede7.cjs
