name: Checks

on: [pull_request]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install
        run: yarn install

      - name: Changes
        run: yarn files changed list
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
